CREATE DATABASE IF NOT EXISTS flightdb;
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS airlinesdb;
CREATE DATABASE IF NOT EXISTS bookingsdb;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';